
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[258] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   95,   93,
       90,   91,   92,   89,   55,   27,   54,   68,   93,   59,
       60,   52,   50,   63,   51,   62,   53,   83,   84,   65,
       61,   48,   64,   46,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   66,
       67,   69,   93,   70,   32,   33,   31,   94,   41,   40,
       36,   38,   37,   45,   43,    0,   56,   57,   75,   75,
       34,   39,    0,    0,    0,    0,    0,   84,   71,   73,
       49,   44,   47,   72,   74,    0,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   15,   74,   74,

       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   42,   32,   30,   28,   29,   41,   36,   35,   88,
        0,    0,   75,    0,    0,   85,    0,   76,    0,    0,
       86,    0,    0,   87,   74,   74,   74,   23,   74,   74,
       74,   74,   74,   74,   74,   18,    3,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
        0,   75,    0,   77,    0,   85,    0,   79,    0,   86,
       81,   81,    0,   87,   87,   74,   20,    2,   74,   74,
       24,   74,   16,    5,   74,   74,   26,   74,   74,   74,
       74,   74,   74,   74,   14,   74,   10,   74,   77,    0,

        0,   78,   79,    0,    0,   80,    0,   81,   81,    0,
       82,   82,   82,   13,    6,   74,   74,    4,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   17,    0,   77,
        0,   79,    0,   81,   81,   81,   74,   74,   25,   74,
       74,    9,   22,   58,   11,   19,   74,   81,   74,   21,
        7,   74,    1,   12,   74,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,    8,    8,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       38,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,    8,   57,    8,   58,   59,   60,   61,

       62,   63,   64,   65,   66,   38,   67,   68,   69,   70,
       71,   72,   38,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   84,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[85] =
    {   0,
        1,    1,    2,    1,    3,    3,    4,    3,    3,    3,
        3,    3,    3,    5,    6,    3,    6,    7,    3,    8,
        8,    8,    8,    3,    3,    3,    3,    3,    8,    9,
        8,    8,    8,    9,   10,   10,   10,   10,   10,   10,
       10,   11,   10,   10,   11,   10,   11,   10,   11,   10,
       10,   10,   10,    3,    4,    3,   10,    8,    9,    8,
        8,    8,    9,   10,   10,   10,   10,   10,   10,   11,
       10,   10,   11,   10,   11,   10,   11,   10,   10,   10,
       10,    3,    3,    3
    } ;

static const flex_int16_t yy_base[274] =
    {   0,
        0,    0,   82,   83,  670,  669,   84,   85,  671,  810,
      810,  810,  810,  810,  643,  810,  810,  655,    0,  810,
      810,  810,  647,  810,  644,   71,   81,   71,   85,  635,
      810,   70,  630,   82,  563,   66,   88,   79,   87,   92,
      109,  107,  119,  113,  134,  128,  135,  131,  116,  810,
      810,  810,  534,  810,    0,  810,  810,  113,    0,  810,
        0,  810,  593,  810,  810,  596,  810,  810,  187,  191,
      810,  810,  162,  206,  177,   95,  196,  212,  810,  810,
      810,  810,  810,  810,  523,  492,  189,  185,  207,  197,
      211,  213,  203,  201,  195,  205,  199,  485,  216,  235,

      241,  242,  227,  240,  237,  252,  245,  259,  249,  263,
      266,  810,    0,  810,  810,  810,    0,    0,  810,  810,
      313,  322,  326,   99,  255,  320,  334,  340,  306,  262,
      346,  487,  268,  332,  323,  336,  313,  444,  326,  327,
      328,  347,  344,  330,  360,  413,  399,  355,  350,  364,
      367,  369,  368,  377,  375,  376,  381,  378,  396,  390,
      439,  443,  184,  447,  428,  451,  375,  453,  461,  467,
      457,  459,  297,  473,  478,  455,  389,  379,  451,  461,
      358,  457,  334,  321,  463,  469,  316,  473,  466,  480,
      479,  491,  502,  501,  294,  509,  274,  510,  530,  554,

      483,  533,  556,  564,  535,  573,  302,  581,  540,  414,
      437,  573,  530,  262,  247,  540,  543,  193,  551,  552,
      572,  573,  571,  581,  574,  583,  588,  184,  544,  602,
      604,  631,    0,  622,    0,  632,  606,  589,  181,  623,
      611,  168,  144,  136,  133,  127,  626,    0,  633,  105,
       77,  634,   69,   64,  637,   45,  810,  698,  709,  720,
      729,  733,  744,  754,  765,  776,  781,  783,  786,  790,
      794,  798,  800
    } ;

static const flex_int16_t yy_def[274] =
    {   0,
      257,    1,  258,  258,  259,  259,  260,  260,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  261,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  257,
      257,  257,  257,  257,  263,  257,  257,  264,  265,  257,
      266,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  267,  257,  257,  257,  257,
      257,  257,  257,  257,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  257,  263,  257,  257,  257,  265,  266,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  268,  257,  269,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      268,  268,  270,  269,  271,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  257,  257,

      257,  257,  257,  257,  257,  257,  268,  272,  268,  270,
      270,  271,  212,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  257,  257,
      257,  257,  273,  272,  234,  234,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  273,  262,  262,
      262,  262,  262,  262,  262,  262,    0,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257
    } ;

static const flex_int16_t yy_nxt[895] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   10,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   35,   35,   41,   35,   35,   42,
       43,   35,   35,   44,   45,   46,   47,   35,   48,   49,
       35,   35,   35,   50,   10,   51,   10,   35,   36,   37,
       38,   39,   40,   35,   35,   41,   35,   42,   43,   35,
       35,   44,   45,   46,   47,   35,   48,   49,   35,   35,
       35,   52,   53,   54,   56,   56,   62,   62,   57,   57,
       69,   70,   70,   70,   71,   80,   81,   63,   63,   72,

       73,   86,   77,   74,   78,   78,   78,   78,   83,   84,
       87,   93,  132,   75,  133,  114,   88,   74,  163,  164,
       86,   76,   86,   89,   90,   86,   94,   91,   95,   73,
       92,   96,   74,   86,   97,   86,   58,   58,   87,  100,
       93,   75,   98,   86,   86,   88,   74,  101,   86,   76,
       99,  111,   89,   90,   94,   91,   95,  102,   92,   96,
      103,   86,   97,   86,  105,   86,  104,  116,  100,   86,
      108,   98,   86,  110,  106,   86,  101,  107,   99,  124,
      111,  125,  126,   86,   86,  102,  109,   86,  103,   86,
       86,   86,   86,  105,  129,  104,  130,  131,  131,  108,

       86,  110,  106,  163,  164,  107,  121,   70,   70,   70,
      123,   70,   70,   70,  109,   69,   70,   70,   70,  122,
      127,  135,  127,  122,   86,  128,  128,  128,  128,   77,
      136,   78,   78,   78,   78,  137,  142,   86,  138,  139,
       86,   86,  144,  146,   74,   86,  143,  145,  122,   86,
      135,   86,  122,   86,  140,   86,  152,   86,  136,   86,
      141,   86,  147,   86,  137,  142,  138,   86,  139,   86,
      144,  146,   86,   74,  143,  145,  148,  149,  150,  129,
      155,  156,  140,   86,  151,  152,  153,  165,  141,  154,
      147,   86,  158,   86,  169,  157,   86,   86,   86,  159,

      173,   86,  160,   86,  148,   86,  149,  150,   86,  155,
      156,  210,  151,  210,  153,   86,  165,  154,   86,   86,
      158,  207,   86,  169,  157,  167,  168,  168,  159,  173,
       86,  160,  121,   70,   70,   70,  161,  124,  161,  166,
      166,  162,  162,  162,  162,  123,   70,   70,   70,  132,
       86,  176,  165,  128,  128,  128,  128,  178,  122,  128,
      128,  128,  128,  129,  175,  170,  170,  170,  177,   86,
      184,  179,   86,  180,  181,  182,  183,   86,  169,   86,
      176,  165,   86,   86,   86,  178,   86,  122,  185,  186,
       86,  187,   86,  175,  167,  168,  168,  177,  184,  179,

       86,  180,  181,   86,  182,  183,   86,  169,  190,  192,
      196,   86,  188,  189,   86,  191,   86,  185,  186,  187,
       86,  193,  194,   86,   86,   86,  195,  197,  257,  198,
      257,   86,   86,   86,   86,   86,  190,   86,  192,  196,
      188,  189,  201,  191,  201,   86,   86,  202,  202,  193,
      194,  257,   86,  257,  195,   86,  197,  198,  162,  162,
      162,  162,  162,  162,  162,  162,  199,  199,  124,   86,
      166,  166,  203,  203,  203,  205,  207,  205,  209,  200,
      206,  206,  206,  165,  129,  204,  170,  170,  170,  208,
      132,  208,  210,  214,  210,  132,  215,  216,  221,  169,

       86,  220,  202,  202,  217,  175,  171,   86,  200,  218,
      213,   86,  165,   86,  204,  219,  222,   86,  208,   86,
      208,  214,   86,  223,  215,   86,  216,  221,  169,   86,
      220,  226,  217,  224,  175,   86,   86,  218,  225,  213,
      227,   86,  228,  219,  210,  222,  210,   86,   86,  199,
      199,  223,  202,  202,  206,  206,  206,   86,   86,  209,
      226,  224,  200,  230,  230,   86,   86,  225,  229,  227,
      229,  228,  208,  230,  230,  203,  203,  203,  231,   86,
      231,  237,  238,  232,  232,  232,  239,  257,  204,  257,
      132,  200,  206,  206,  206,  233,   86,  233,  240,   86,

      234,  208,  241,  242,  245,  213,  120,   86,   86,  237,
      238,  119,  243,  236,  244,  239,  112,  204,  246,   86,
      247,  230,  230,  232,  232,  232,  240,   86,   86,   86,
       86,  241,  242,  245,  213,  250,  257,   86,  257,   86,
      243,  234,  236,  244,   86,   86,  233,  246,  233,  247,
      232,  232,  232,  249,  236,  251,   82,  252,   79,  253,
       68,   67,   86,  250,   65,  254,  255,   86,  256,   64,
      257,   60,   60,  257,  257,  257,  257,  257,  257,   86,
      257,  249,   86,  236,  251,  252,  257,  257,  253,   86,
       86,  257,  257,   86,  254,  255,  257,  256,   55,   55,

       55,   55,   55,   55,   55,   55,   55,   55,   55,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       85,   85,   85,   85,  113,  257,  113,  257,  113,  113,
      113,  113,  113,  113,  113,  115,  257,  115,  257,  257,
      257,  257,  115,  257,  115,  117,  257,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  118,  257,  118,  118,
      257,  118,  118,  118,  118,  118,  118,  134,  134,  134,
      172,  172,  174,  174,  174,  211,  257,  211,  211,  212,

      212,  212,  212,  235,  257,  235,  235,  248,  248,    9,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257

    } ;

static const flex_int16_t yy_chk[895] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    7,    8,    3,    4,
       26,   26,   26,   26,   27,   32,   32,    7,    8,   27,

       28,  256,   29,   28,   29,   29,   29,   29,   34,   34,
       36,   38,   76,   28,   76,   58,   37,   29,  124,  124,
      254,   28,   36,   37,   37,  253,   39,   37,   39,   28,
       37,   40,   28,  251,   40,   38,    3,    4,   36,   42,
       38,   28,   41,   39,   37,   37,   29,   43,   40,   28,
       41,   49,   37,   37,   39,   37,   39,   44,   37,   40,
       44,  250,   40,   42,   46,   41,   45,   58,   42,   44,
       47,   41,   49,   48,   46,   43,   43,   46,   41,   73,
       49,   73,   73,  246,   46,   44,   47,   48,   44,  245,
       45,   47,  244,   46,   75,   45,   75,   75,   75,   47,

      243,   48,   46,  163,  163,   46,   69,   69,   69,   69,
       70,   70,   70,   70,   47,   77,   77,   77,   77,   69,
       74,   87,   74,   70,  242,   74,   74,   74,   74,   78,
       88,   78,   78,   78,   78,   89,   93,  239,   90,   91,
      228,   88,   95,   97,   78,   87,   94,   96,   69,  218,
       87,   95,   70,   90,   92,   97,  103,   94,   88,   93,
       92,   96,   99,   89,   89,   93,   90,   91,   91,   92,
       95,   97,   99,   78,   94,   96,  100,  101,  102,  130,
      106,  107,   92,  103,  102,  103,  104,  125,   92,  105,
       99,  100,  109,  105,  130,  108,  104,  101,  102,  110,

      133,  107,  111,  215,  100,  109,  101,  102,  106,  106,
      107,  173,  102,  173,  104,  108,  125,  105,  214,  110,
      109,  207,  111,  130,  108,  129,  129,  129,  110,  133,
      197,  111,  121,  121,  121,  121,  122,  126,  122,  126,
      126,  122,  122,  122,  122,  123,  123,  123,  123,  134,
      195,  135,  126,  127,  127,  127,  127,  137,  123,  128,
      128,  128,  128,  131,  134,  131,  131,  131,  136,  137,
      144,  139,  187,  140,  141,  142,  143,  184,  131,  135,
      135,  126,  139,  140,  141,  137,  144,  123,  145,  148,
      183,  149,  136,  134,  167,  167,  167,  136,  144,  139,

      143,  140,  141,  142,  142,  143,  149,  131,  152,  154,
      158,  148,  150,  151,  181,  153,  145,  145,  148,  149,
      150,  155,  156,  151,  153,  152,  157,  159,  210,  160,
      210,  155,  156,  154,  158,  178,  152,  157,  154,  158,
      150,  151,  165,  153,  165,  177,  160,  165,  165,  155,
      156,  211,  159,  211,  157,  147,  159,  160,  161,  161,
      161,  161,  162,  162,  162,  162,  164,  164,  166,  146,
      166,  166,  168,  168,  168,  169,  171,  169,  172,  164,
      169,  169,  169,  166,  170,  168,  170,  170,  170,  171,
      174,  172,  175,  176,  175,  175,  179,  180,  189,  170,

      138,  188,  201,  201,  182,  174,  132,  179,  164,  185,
      175,  176,  166,  182,  168,  186,  190,  180,  171,  185,
      172,  176,  189,  191,  179,  186,  180,  189,  170,  188,
      188,  194,  182,  192,  174,  191,  190,  185,  193,  175,
      196,   98,  198,  186,  213,  190,  213,  192,   86,  199,
      199,  191,  202,  202,  205,  205,  205,  194,  193,  209,
      194,  192,  199,  229,  229,  196,  198,  193,  200,  196,
      200,  198,  209,  200,  200,  203,  203,  203,  204,   85,
      204,  216,  217,  204,  204,  204,  219,  212,  203,  212,
      212,  199,  206,  206,  206,  208,  216,  208,  220,  217,

      208,  209,  221,  222,  225,  212,   66,  219,  220,  216,
      217,   63,  223,  208,  224,  219,   53,  203,  226,   35,
      227,  230,  230,  231,  231,  231,  220,  223,  221,  222,
      225,  221,  222,  225,  212,  238,  234,  224,  234,  226,
      223,  234,  208,  224,  227,  238,  236,  226,  236,  227,
      232,  232,  232,  237,  234,  240,   33,  241,   30,  247,
       25,   23,  237,  238,   18,  249,  252,  241,  255,   15,
        9,    6,    5,    0,    0,    0,    0,    0,    0,  240,
        0,  237,  247,  234,  240,  241,    0,    0,  247,  249,
      252,    0,    0,  255,  249,  252,    0,  255,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      262,  262,  262,  262,  263,    0,  263,    0,  263,  263,
      263,  263,  263,  263,  263,  264,    0,  264,    0,    0,
        0,    0,  264,    0,  264,  265,    0,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  266,    0,  266,  266,
        0,  266,  266,  266,  266,  266,  266,  267,  267,  267,
      268,  268,  269,  269,  269,  270,    0,  270,  270,  271,

      271,  271,  271,  272,    0,  272,  272,  273,  273,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical_analyzer.l"
#line 2 "lexical_analyzer.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <math.h>
    #include "syntax_analyzer.tab.h"

    FILE *fp;
    char filename[1024];
    int line_number = 1;
    int errors = 0;

    int integer_binary_to_decimal(char *number) {
        int decimal = 0;
        int base = 1;
        int len = strlen(number);
        int i;
        for (i = len - 1; i >= 0; i--) {
            if (number[i] == '1') {
                decimal += base;
            }
            base = base * 2;
        }
        return decimal;
    }

    int integer_octal_to_decimal(char *number) {
        int decimal = 0;
        int base = 1;
        int len = strlen(number);
        printf("number is %s\n", number);

        for (int i = len - 1; i >= 0; i--) {
            decimal += (number[i] - '0') * base;
            base = base * 8;
        }
        return decimal;
    }

    int integer_hexadecimal_to_decimal(char *number) {
        int decimal = 0;
        int base = 1;
        int len = strlen(number);

        for (int i = len - 1; i >= 0; i--) {
            if (number[i] >= '0' && number[i] <= '9') {
                decimal += (number[i] - '0') * base;
            } else if (number[i] >= 'A' && number[i] <= 'F') {
                decimal += (number[i] - 'A' + 10) * base;
            } else if (number[i] >= 'a' && number[i] <= 'f') {
                decimal += (number[i] - 'a' + 10) * base;
            }
            base = base * 16;
        }
        return decimal;
    }

    double convertExponentialPart(const char *str) {
        return strtod(str, NULL); // Convert exponential notation directly
    }

    double convertFractionalPart(const char *fraction, int base) 
    {
        double result = 0.0;
        int len = strlen(fraction);
        for (int i = 0; i < len; i++) {
            if (fraction[i] >= '0' && fraction[i] <= '9') {
                result += (fraction[i] - '0') / pow(base, i + 1);
            } else if (fraction[i] >= 'A' && fraction[i] <= 'F') {
                result += (10 + fraction[i] - 'A') / pow(base, i + 1);
            } else if (fraction[i] >= 'a' && fraction[i] <= 'f') {
                result += (10 + fraction[i] - 'a') / pow(base, i + 1);
            }
        }
        return result;
    }

    double convertToFloat(const char *text) 
    {
        char *endPtr;
        double result = 0.0;
        if (strncmp(text, "0x", 2) == 0) { // Hexadecimal
            result = strtod(text, &endPtr);
        } else if (strncmp(text, "0o", 2) == 0) { // Octal
            result = strtoul(text + 2, &endPtr, 8);
        } else if (strncmp(text, "0b", 2) == 0) { // Binary
            result = strtoul(text + 2, &endPtr, 2);
        } else { // Decimal or exponential
            result = strtod(text, &endPtr);
        }

        if (*endPtr == '.') { // Handle fractional part
            result += convertFractionalPart(endPtr + 1, (*text == '0' && *(text + 1) == 'x') ? 16 : 10);
            endPtr = strchr(endPtr + 1, 'E');
        }

        if (endPtr && *endPtr == 'E') { // Handle exponential part
            result *= pow(10, convertExponentialPart(endPtr + 1));
        }

        return result;
    }

    void error_handler()
    {
        printf("Error #%d found at line %d.\n", errors, line_number);  

        // Ανοίγω το αρχείο κώδικα
        FILE *fp1 = fopen(filename, "r");
        int i = 1;
        char line_text[4096];
        // διαβάζω line_number γραμμές ώστε να υπάρχει στο line_text 
        // η γραμμή στην οποία έγινε το σφάλμα
        while (i <= line_number)
        {
            memset(line_text, 0, 4096);     // διαγράφει ό,τι χαρακτήρες είχε line_text 
            fgets(line_text,  4096, fp1);   // διαβάζει την επομένη γραμμή από το αρχείο
            i++;                            // και την αποθηκεύει στο line_text
        }
        // Μετά το τέλος του while το line_text περιέχει όλη τη γραμμή στην οποία 
        // έχει γίνει λεκτικό σφάλμα
        printf("The error line is:\n%s\n", line_text);
        fclose(fp1);

        // Σε περίπτωση που έχουμε δύο λεκτικά σφάλματα σταματάμε το πρόγραμμα
        if (errors==2) 
        {
            printf("You have code issues. Fix them and then come back.\n"); 
            exit(1);
        }
    }

#line 865 "lex.yy.c"

#line 867 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENTS_SINGLELINE 2
#define COMMENTS_MULTILINE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 142 "lexical_analyzer.l"

#line 1089 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 258 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 810 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 143 "lexical_analyzer.l"
{printf("Found TYPEDEF\n");     return T_TYPEDEF;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 144 "lexical_analyzer.l"
{printf("Found CHAR\n");        return T_CHAR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 145 "lexical_analyzer.l"
{printf("Found INT\n");         return T_INT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 146 "lexical_analyzer.l"
{printf("Found FLOAT\n");       return T_FLOAT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "lexical_analyzer.l"
{printf("Found ENUM\n");        return T_ENUM;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 148 "lexical_analyzer.l"
{printf("Found CLASS\n");       return T_CLASS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 149 "lexical_analyzer.l"
{printf("Found PRIVATE\n");     return T_PRIVATE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "lexical_analyzer.l"
{printf("Found PROTECTED\n");   return T_PROTECTED;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 151 "lexical_analyzer.l"
{printf("Found PUBLIC\n");      return T_PUBLIC;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 152 "lexical_analyzer.l"
{printf("Found VOID\n");        return T_VOID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 153 "lexical_analyzer.l"
{printf("Found STATIC\n");      return T_STATIC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "lexical_analyzer.l"
{printf("Found CONTINUE\n");    return T_CONTINUE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 155 "lexical_analyzer.l"
{printf("Found BREAK\n");       return T_BREAK;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 156 "lexical_analyzer.l"
{printf("Found THIS\n");        return T_THIS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 "lexical_analyzer.l"
{printf("Found IF\n");          return T_IF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 158 "lexical_analyzer.l"
{printf("Found ELSE\n");        return T_ELSE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 159 "lexical_analyzer.l"
{printf("Found WHILE\n");       return T_WHILE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 160 "lexical_analyzer.l"
{printf("Found FOR\n");         return T_FOR;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 161 "lexical_analyzer.l"
{printf("Found SWITCH\n");      return T_SWITCH;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 162 "lexical_analyzer.l"
{printf("Found CASE\n");        return T_CASE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 163 "lexical_analyzer.l"
{printf("Found DEFAULT\n");     return T_DEFAULT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 164 "lexical_analyzer.l"
{printf("Found RETURN\n");      return T_RETURN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 165 "lexical_analyzer.l"
{printf("Found CIN\n");         return T_CIN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 166 "lexical_analyzer.l"
{printf("Found COUT\n");        return T_COUT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 167 "lexical_analyzer.l"
{printf("Found LENGTH\n");      return T_LENGTH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 168 "lexical_analyzer.l"
{printf("Found MAIN\n");        return T_MAIN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 170 "lexical_analyzer.l"
{ BEGIN(STRING);    memset(yylval.str, 0, 4096);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 171 "lexical_analyzer.l"
{ strcat(yylval.str, yytext); /* Βάζω στο τέλος του str ό,τι διάβασα τώρα από την ΚΕ*/}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 172 "lexical_analyzer.l"
{ strcat(yylval.str, yytext); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 173 "lexical_analyzer.l"
{ line_number++; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 174 "lexical_analyzer.l"
{ BEGIN(INITIAL); printf("String is finished: %s\n", yylval.str); return T_STRING; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 175 "lexical_analyzer.l"
{ strcat(yylval.str, yytext); }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 176 "lexical_analyzer.l"
{ line_number++; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 179 "lexical_analyzer.l"
{ BEGIN(COMMENTS_MULTILINE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 180 "lexical_analyzer.l"
{ BEGIN(INITIAL); printf("Multiline comment section ended\n");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 181 "lexical_analyzer.l"
{ ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 182 "lexical_analyzer.l"
{ ; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 183 "lexical_analyzer.l"
{ line_number++; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 185 "lexical_analyzer.l"
{ BEGIN(COMMENTS_SINGLELINE); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 186 "lexical_analyzer.l"
{ BEGIN(INITIAL); line_number++; printf("Single line comment section ended\n"); } 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 187 "lexical_analyzer.l"
{ ; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 190 "lexical_analyzer.l"
{strcpy(yylval.str, "||");      printf("Found OROP || %d\n", T_OROP);        return T_OROP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 191 "lexical_analyzer.l"
{strcpy(yylval.str, "&&");      printf("Found ANDOP && %d\n", T_ANDOP);       return T_ANDOP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 192 "lexical_analyzer.l"
{strcpy(yylval.str, "==");      printf("Found EQUOP == %d\n", T_EQUOP);       return T_EQUOP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 193 "lexical_analyzer.l"
{strcpy(yylval.str, "!=");      printf("Found EQUOP\n");       return T_EQUOP;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 194 "lexical_analyzer.l"
{strcpy(yylval.str, ">");       printf("Found RELOP > %d\n", T_RELOP);        return T_RELOP;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 195 "lexical_analyzer.l"
{strcpy(yylval.str, ">=");      printf("Found RELOP >= %d\n", T_RELOP);        return T_RELOP;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 196 "lexical_analyzer.l"
{strcpy(yylval.str, "<");       printf("Found RELOP\n");        return T_RELOP;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 197 "lexical_analyzer.l"
{strcpy(yylval.str, "<=");      printf("Found RELOP\n");        return T_RELOP;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 198 "lexical_analyzer.l"
{strcpy(yylval.str, "+");       printf("Found ADDOP\n");        return T_ADDOP;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 199 "lexical_analyzer.l"
{strcpy(yylval.str, "-");       printf("Found ADDOP\n");        return T_ADDOP;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 200 "lexical_analyzer.l"
{strcpy(yylval.str, "*");       printf("Found MULOP\n");        return T_MULOP;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 201 "lexical_analyzer.l"
{strcpy(yylval.str, "/");       printf("Found MULOP\n");        return T_MULOP;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 202 "lexical_analyzer.l"
{strcpy(yylval.str, "%");       printf("Found MULOP\n");        return T_MULOP;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 203 "lexical_analyzer.l"
{strcpy(yylval.str, "!");       printf("Found NOTOP\n");        return T_NOTOP;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 204 "lexical_analyzer.l"
{strcpy(yylval.str, "++");      printf("Found INCDEC\n");       return T_INCDEC;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 205 "lexical_analyzer.l"
{strcpy(yylval.str, "--");      printf("Found INCDEC\n");       return T_INCDEC;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 206 "lexical_analyzer.l"
{strcpy(yylval.str, "SIZEOF");  printf("Found SIZEOP\n");       return T_SIZEOP;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 208 "lexical_analyzer.l"
{strcpy(yylval.str, "(");  printf("Found LPAREN\n");        return T_LPAREN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 209 "lexical_analyzer.l"
{strcpy(yylval.str, ")");  printf("Found RPAREN\n");        return T_RPAREN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 210 "lexical_analyzer.l"
{strcpy(yylval.str, ";");  printf("Found SEMI\n");          return T_SEMI;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 211 "lexical_analyzer.l"
{strcpy(yylval.str, ".");  printf("Found DOT\n");           return T_DOT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 212 "lexical_analyzer.l"
{strcpy(yylval.str, ",");  printf("Found COMMA\n");         return T_COMMA;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 213 "lexical_analyzer.l"
{strcpy(yylval.str, "=");  printf("Found ASSIGN\n");        return T_ASSIGN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 214 "lexical_analyzer.l"
{strcpy(yylval.str, ":");  printf("Found COLON\n");         return T_COLON;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 215 "lexical_analyzer.l"
{strcpy(yylval.str, "[");  printf("Found LBRACK\n");        return T_LBRACK;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 216 "lexical_analyzer.l"
{strcpy(yylval.str, "]");  printf("Found RBRACK\n");        return T_RBRACK;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 217 "lexical_analyzer.l"
{strcpy(yylval.str, "&");  printf("Found REFER\n");         return T_REFER;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 218 "lexical_analyzer.l"
{strcpy(yylval.str, "{");  printf("Found LBRACE\n");        return T_LBRACE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 219 "lexical_analyzer.l"
{strcpy(yylval.str, "}");  printf("Found RBRACE\n");        return T_RBRACE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 220 "lexical_analyzer.l"
{strcpy(yylval.str, "::");  printf("Found METH\n");         return T_METH;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 221 "lexical_analyzer.l"
{strcpy(yylval.str, ">>");  printf("Found INP\n");          return T_INP;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 222 "lexical_analyzer.l"
{strcpy(yylval.str, "<<");  printf("Found OUT\n");          return T_OUT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 224 "lexical_analyzer.l"
{strcpy(yylval.str, yytext);  printf("Found ID named %s\n", yylval.str);  return T_ID;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 226 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 227 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 228 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 229 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 230 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 231 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 232 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 233 "lexical_analyzer.l"
{ yylval.real = convertToFloat(yytext);   printf("Found FCONST value %lf\n", yylval.real); return T_FCONST;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 235 "lexical_analyzer.l"
{yylval.integer = 0;                                        printf("Found ICONST value %d\n", yylval.integer);      return T_ICONST;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 236 "lexical_analyzer.l"
{yylval.integer = atoi(yytext);                             printf("Found ICONST value %d\n", yylval.integer);      return T_ICONST;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 237 "lexical_analyzer.l"
{yylval.integer = integer_binary_to_decimal(yytext);        printf("Found ICONST value %d\n", yylval.integer);      return T_ICONST;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 238 "lexical_analyzer.l"
{yylval.integer = integer_octal_to_decimal(yytext);         printf("Found ICONST value %d\n", yylval.integer);      return T_ICONST;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 239 "lexical_analyzer.l"
{yylval.integer = integer_hexadecimal_to_decimal(yytext);   printf("Found ICONST value %d\n", yylval.integer);      return T_ICONST;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 241 "lexical_analyzer.l"
{yylval.character = yytext[1]; printf("Found CHAR value %s\n", yytext);    return T_CCONST;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 242 "lexical_analyzer.l"

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 243 "lexical_analyzer.l"

	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 244 "lexical_analyzer.l"
{line_number++;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 245 "lexical_analyzer.l"

	YY_BREAK
case 93:
YY_RULE_SETUP
#line 247 "lexical_analyzer.l"
{errors++; error_handler(); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 249 "lexical_analyzer.l"
ECHO;
	YY_BREAK
#line 1621 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENTS_SINGLELINE):
case YY_STATE_EOF(COMMENTS_MULTILINE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 258 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 258 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 257);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "lexical_analyzer.l"


